sitesiteTitle = 'Bánh Ngon Mỗi Ngày'
siteDescr = 'Bánh Ngon Mỗi Ngày'
siteDescription = "Cùng tới với chúng tôi, vui vẻ cùng banhngonmoingay.xyz."
siteUrl = "http://banhngonmoingay.xyz"
siteBandcampUrl = 'http://banhngonmoingay.xyz'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/bepnhaty'
siteDiscogsUrl = ''
siteTwitterUrl = 'https://twitter.com'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com'
siteYoutubeUrl = 'https://www.youtube.com/channel/relax24hr'

linkPrefix = '/'
