sitesiteTitle = 'Ăn Uống Mỗi Ngày'
siteDescr = 'Ăn Uống Mỗi Ngày'
siteDescription = "Cùng tới với chúng tôi, vui vẻ cùng binhduongbuy."
siteUrl = "http://anuongmoingay.net"
siteBandcampUrl = 'http://anuongmoingay.net'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/Món-Ngon-Bình-Dương-185286918690182'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/nihon_ne'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com/nihonne'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
